from ti_system import *
#Save repair.
suserid=str(recall_value("loggedinuser"))
def Delete():
    if suserid=="0" or suserid==0:print(">>Login an account first!");return 1
    store_value("playery"+suserid,95)
    store_value("playerx"+suserid,95)
    store_value("plspd"+suserid,5)
    store_value("kingignores"+suserid,0)
    store_value("v_hev"+suserid,0)
    store_value("emptysave"+suserid,1)
    store_value("inclip9"+suserid,0)
    store_value("inclip357"+suserid,0)
    store_value("wpnslt"+suserid,0)
    store_value("v_live"+suserid,100)
    store_value("weapon_crb"+suserid,0)
    store_value("weapon_pcn"+suserid,0)
    store_value("weapon_pst"+suserid,0)
    store_value("weapon_357"+suserid,0)
    store_value("mapslt"+suserid,0)
    store_value("ammo9"+suserid,0)
    store_value("plh"+suserid,5)
    store_value("plw"+suserid,5)
    store_value("plr"+suserid,0)
    store_value("plg"+suserid,0)
    store_value("plb"+suserid,0)
    store_value("ammo357"+suserid,0)
    store_value("item_suit"+suserid,0)
    print(">>File deleted.")
    return 0
if __name__=="__main__":Delete()